### ISSUE TITLE
stimela doesn't see pfb workers inside kubernetes cab definition

### ISSUE THREAD

**Issue by landmanbester** [landmanbester/stimecipes#1]
@o-smirnov I based [this](https://github.com/landmanbester/lbstimecipes/blob/37b7950273a89d686a476b7f008665f99a4a0110/pfbkube.yaml#L11) cab definition on the corresponding one for QuartiCal [here](https://github.com/caracal-pipeline/stimela2/blob/kube/tests/stimela_tests/test_kube.yml). For some reason I get
```
$ stimela help ~/software/lbstimecipes/pfbkube.yaml pfbkube
2022-07-25 09:16:55 STIMELA INFO: starting
2022-07-25 09:16:55 STIMELA INFO: loaded full configuration from cache
2022-07-25 09:16:55 STIMELA INFO: backend is native
2022-07-25 09:16:55 STIMELA INFO: saving config dependencies to ./stimela.config.deps
2022-07-25 09:16:55 STIMELA INFO: loading recipe/config /home/bester/software/lbstimecipes/pfbkube.yaml
Traceback (most recent call last):
  File "/home/bester/.venv/pfb/bin/stimela", line 33, in <module>
    sys.exit(load_entry_point('stimela', 'console_scripts', 'stimela')())
  File "/home/bester/.venv/pfb/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/bester/.venv/pfb/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/bester/.venv/pfb/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/bester/.venv/pfb/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/bester/.venv/pfb/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/bester/software/stimela2/stimela/commands/help.py", line 76, in help
    conf, recipe_deps = load_recipe_file(item)
  File "/home/bester/software/stimela2/stimela/commands/run.py", line 30, in load_recipe_file
    conf, deps = configuratt.load(filename, use_sources=[stimela.CONFIG])
  File "/home/bester/software/stimela2/scabha/configuratt.py", line 556, in load
    conf, deps = _resolve_config_refs(subconf, pathname=path, location=location, name=name, includes=includes, use_sources=use_sources, include_path=include_path)
  File "/home/bester/software/stimela2/scabha/configuratt.py", line 287, in _resolve_config_refs
    value1, deps = _resolve_config_refs(value, pathname=pathname, name=name,
  File "/home/bester/software/stimela2/scabha/configuratt.py", line 287, in _resolve_config_refs
    value1, deps = _resolve_config_refs(value, pathname=pathname, name=name,
  File "/home/bester/software/stimela2/scabha/configuratt.py", line 266, in _resolve_config_refs
    merge_sections = [_lookup_name(name, *use_sources) for name in merge_sections]
  File "/home/bester/software/stimela2/scabha/configuratt.py", line 266, in <listcomp>
    merge_sections = [_lookup_name(name, *use_sources) for name in merge_sections]
  File "/home/bester/software/stimela2/scabha/configuratt.py", line 75, in _lookup_name
    raise NameError(f"unknown key {name}")
NameError: unknown key pfb.init
```
Strangely, I can get help on pfb.init if I uncomment the pfbkube cab definition
```
$ stimela help ~/software/lbstimecipes/pfbkube.yaml pfb.init                                                                                                                                                1 ↵
2022-07-25 09:17:55 STIMELA INFO: starting
2022-07-25 09:17:55 STIMELA INFO: loaded full configuration from cache
2022-07-25 09:17:55 STIMELA INFO: backend is native
2022-07-25 09:17:55 STIMELA INFO: saving config dependencies to ./stimela.config.deps
2022-07-25 09:17:55 STIMELA INFO: loading recipe/config /home/bester/software/lbstimecipes/pfbkube.yaml
⠦  stimela ⠦ starting 0:00:00  stimela help /home/bester/software/lbstimecipes/pfbkube.yaml pfb.init
└── Cab: pfb.init
    ├── command: (pfb.workers.init)init
    ├── Required inputs:
    │   └── ms               str  Path to measurement set.
    │       output_filename  str  Basename of output
    │       nband            int  Number of imaging bands
    └── Optional inputs:
        └── host_address         str    Address where the distributed client lives. Will use a local cluster if no address is provided
            nworkers             int    Number of worker processes
            nthreads_per_worker  int    Number of threads per worker process
            nvthreads            int    Number of threads used to scale vertically (eg. for FFTs)
            nthreads             int    Total number of threads to use between all processes. Will use all available resources by default
            mem_limit            int    Memory limit. Will use all available resources by default
            scheduler            str    distributed | single-threaded/sync | threads [default: sync]
            overwrite            bool   Allow overwrite of output xds [default: False]
            data_column          str    Data column to image. Must be the same across MSs [default: DATA]
            weight_column        str    Column containing natural weights. Must be the same across MSs [default: WEIGHT_SPECTRUM]
            sigma_column         str    Column containing standard devations. \ Will be used to initialise natural weights if detected. \ Must be the same across MSs
            flag_column          str    Column containing data flags. Must be the same across MSs [default: FLAG]
            gain_table           str    Path to Quartical gain table containing NET gains.There must be a table for each MS and glob(ms) and glob(gt) should match up.
            gain_term            str    Which gain term to use. Default is NET [default: NET]
            product              str    Imaging products to produce. Options are I, Q, U, V. \ Only single Stokes products are currently supported [default: I]
            utimes_per_chunk     int    Unique times per row chunk [default: -1]
            group_by_field       bool   Split data by field [default: True]
            group_by_ddid        bool   Split data by DDID [default: True]
            group_by_scan        bool   Split data by scan [default: True]
            precision            str    "single" or "double" [default: double]
            bda_decorr           float  BDA decorrelation factor. Only has an effect if less than one [default: 1.0]
            beam_model           str    Beam model to use
            max_field_of_view    float  Field of view in degrees [default: 3.0]
```
Any idea what could be going wrong here?

**Comment by landmanbester** [comment]
The issue was the period in ```pfb.init```. All workers are now defined with an underscore i.e. ```pfb_init```
